# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustivel', models.CharField(choices=[('Gasolina', 'gasolina'), ('Alcool', 'alcool'), ('Diesel', 'diesel')], default='GASOLINA', max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('quilometros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combustivel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Combustivel')),
                ('destino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Destino')),
                ('origem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Origem')),
            ],
        ),
    ]
