# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
