# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160220_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='slug',
            field=models.SlugField(),
        ),
    ]
