# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160220_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='total_preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, unique=True),
        ),
    ]
